title: Andre Holzer's Github # your name (or website title) here
logo: "/images/w0Gzhvp2_400x400.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Student @ Univeristy of Cambridge
  <br><br>
  Researching algae-omics
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
