#title: Andre Holzer's Github # your name (or website title) here
logo: "/images/Andre_Holzer-01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Candidate @ Univeristy of Cambridge & Gates Cambridge Scholar 
  <br><br>
  working on  Epigenetics | Bioinformatics | Transposons | Metagenomics | Algae | Chlamydomonas 
  <br>
  <img src="https://github.com/AndreHolzer/AndreHolzer.github.io/raw/master/images/ORCID-iD_icon-32x32.png" width="10" /><a href="https://orcid.org/0000-0003-2439-6364">  ORCID iD</a> 

  <ul class="social-icons">
    <li><a href="https://www.linkedin.com/in/andre-holzer-gatescambridge"><img src="https://github.com/AndreHolzer/AndreHolzer.github.io/raw/master/images/Linkedin_1.png" width="30" /></a></li>
    <li><a href="https://github.com/AndreHolzer/"><img src="https://github.com/AndreHolzer/AndreHolzer.github.io/raw/master/images/Github_1.png" width="30" /></a></li>
    <li><a href="https://twitter.com/andreholzer?lang=en"><img src="https://github.com/AndreHolzer/AndreHolzer.github.io/raw/master/images/Twitter_1.png" width="30" /></a></li>
  </ul>
  
  <a href="https://www.plantsci.cam.ac.uk/directory/holzer-andre">
    <img alt="Qries" src="https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/31562251_243549129544807_5177695355878476224_n.png?_nc_cat=111&_nc_sid=85a577&_nc_ohc=-n5hsgSmDbgAX_dxi0t&_nc_ht=scontent-frx5-1.xx&oh=f6732eb123eae8dbbaaf2dd8e1870397&oe=5EA9CFA1" width="50%">
  </a>
  
  <a href="https://www.gatescambridge.org/members-area/connect/directory/scholar/9642">
    <img alt="Qries" src="https://aas.princeton.edu/sites/aas/files/styles/pwds_featured_image/public/events/gates_cambridge_logo_0.png?itok=vKhWSzGL" width="50%">
  </a>
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here