#title: Andre Holzer's Github # your name (or website title) here
logo: "/images/Andre_Holzer-01.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Candidate @ Univeristy of Cambridge & Gates Cambridge Scholar 
  <br><br>
  working on  Epigenetics | Bioinformatics | Transposons | Metagenomics | Algae | Chlamydomonas 
  <br><br>
  <a href="https://www.linkedin.com/in/andre-holzer-gatescambridge">LinkedIn Profile</a> 
  <br>
  <a href="https://orcid.org/0000-0003-2439-6364">ORCID iD</a> 
  <br>
  <a href="https://twitter.com/andreholzer?lang=en">Twitter Profile</a> 
  <br>
  <a href="">GitHub Profile</a> 
  
  <a href="https://www.gatescambridge.org/members-area/connect/directory/scholar/9642">
    <img alt="Qries" src="https://cdn5.euraxess.org/sites/default/files/styles/news_and_events_details/public/news/gates-cambridge.png?itok=ShiS8eOZ">
  </a>
  
  <a href="https://www.plantsci.cam.ac.uk/directory/holzer-andre">
    <img alt="Qries" src="https://www.cam.ac.uk/sites/www.cam.ac.uk/files/inner-images/logo.jpg">
  </a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
